Repository 1298se/Contrail-Web, pull requests merged in 2019-06, with the labels that each got.

#30 Added nodemon
  .vscode/launch.json
  .vscode/settings.json
  README.md
  contrail-api/README.md
  contrail-api/dist/server.js
  contrail-api/nodemon.json
  contrail-api/package-lock.json
  contrail-api/package.json
  contrail-api/src/server.ts
  package-lock.json
  package.json
Labels: Platform

#34 Cw 33
  contrail-ui/.eslintrc.json
  contrail-ui/package-lock.json
  contrail-ui/package.json
Labels: Platform

#38 added MUI theme
  contrail-ui/src/index.js
  contrail-ui/theme.js
Labels: Platform

#43 Added Typescript and redux to UI
  contrail-ui/.eslintrc.json
  contrail-ui/README.md
  contrail-ui/package-lock.json
  contrail-ui/package.json
  contrail-ui/src/App.css
  contrail-ui/src/App.js
  contrail-ui/src/App.test.tsx
  contrail-ui/src/App.tsx
  contrail-ui/src/actions/index.tsx
  contrail-ui/src/components/Auth/Auth.css
  contrail-ui/src/components/Auth/Auth.test.tsx
  contrail-ui/src/components/Auth/Auth.tsx
  contrail-ui/src/components/Files/Files.css
  contrail-ui/src/components/Files/Files.test.tsx
  contrail-ui/src/components/Files/Files.tsx
  contrail-ui/src/constants/index.tsx
  contrail-ui/src/containers/Auth.tsx
  contrail-ui/src/index.css
  contrail-ui/src/index.js
  contrail-ui/src/index.tsx
  contrail-ui/src/react-app-env.d.ts
  contrail-ui/src/reducers/index.tsx
  contrail-ui/src/serviceWorker.js
  contrail-ui/src/theme.js
  contrail-ui/src/types/index.tsx
  contrail-ui/tsconfig.json
  contrail-ui/tslint.json
Labels: Platform

#52 modified auth utils
  contrail-ui/src/components/auth/authStyles.ts
  contrail-ui/src/components/auth/login-form/LoginForm.tsx
  contrail-ui/src/components/auth/register-form/RegisterForm.tsx
  contrail-ui/src/utils/auth-utils.ts
Labels: UI

#57 fixed main layout
  contrail-ui/src/components/main/MainFrame.tsx
  contrail-ui/src/components/main/main-app-bar/MainAppBar.tsx
Labels: bug

#59 osong-fix/userNoDisplayName
  contrail-ui/src/components/auth/login-form/LoginForm.tsx
  contrail-ui/src/components/auth/register-form/RegisterForm.tsx
Labels: bug

#48 Add express backend for auth
  contrail-api/src/firebaseapp.ts
  contrail-api/src/routes/auth.ts
  contrail-api/src/server.ts
  contrail-ui/package-lock.json
Labels: API, enhancement
